### ISSUE TITLE
problem 1m

### ISSUE THREAD

**Issue by beatricemagistro** [UW-POLS503/Assignment_01#10]
@jrnold  @CasAndreu  I don't understand this: m. For all years, calculate the median of the country average years of education all countries? Return this as a data-frame. Hint: use dplyr functions: group_by, filter, summarize. Plot the median of the years of education for all years using a line. Also show the original data.

Are we supposed to do this for every year and every country? I was using group_by, mutate and arrange. But I don't think that's right. 

Thanks!

**Comment by jrnold** [comment]
Yes. Your data frame should have the following columns:
- year: 
- education: Median of the average years of education. Calculated over all countries.

I realize you don't need `filter` to do this.

If you are using arrange, I presume that you are trying to sort and get the median. You should simply use `median` to calculate the median.

**Comment by beatricemagistro** [comment]
Thank you!
