### ISSUE TITLE
2.a

### ISSUE THREAD

**Issue by SteveOtterman** [UW-POLS503/Assignment_01#12]
Greetings! For 2a, when I try to run the regressions like this:

anscombe2 %>% group_by(dataset) %>% summarise(meanx = mean(x), meany = mean(y), cor = cor(x, y), lm = lm(y ~ x, data = .))

I get the error message: "Error: invalid term in model formula."

I've tinkered with it a bunch now, but can't run the regressions. How can I properly run the regressions within the summarise command?

Thanks!

**Comment by jrnold** [comment]
The problem appears to be the way that summarize evaluates the names of variables and how that interacts with `lm`. Without going into details, R does some crazy stuff to evaluate the [names of variables](http://adv-r.had.co.nz/Computing-on-the-language.html) so you don't have to prefix everything with `$` or `[[` in these functions. 

You could get this working by running 

``` r
anscombe2 %>% group_by(dataset) %>% summarise(meanx = mean(x), meany = mean(y), cor = cor(x, y), lm = list(lm(.$y ~ .$x,)))
```

But then the `lm` column will be a `list` (yes, columns in data frames can be lists, which can be incredibly useful, though an advanced feature).

It's probably easier to work with this using the `do` function with the **broom** function `tidy`. See the [vignette for broom and dplyr](https://cran.r-project.org/web/packages/broom/vignettes/broom_and_dplyr.html). Here's a template of what your code should look like. 

``` r
... %>%
   group_by(...) %>%
   do(tidy(lm(....)))
```

Your dataframe should look like this

```
  dataset        term  estimate std.error statistic     p.value
     (chr)       (chr)     (dbl)     (dbl)     (dbl)       (dbl)
1        1 (Intercept) 3.0000909 1.1247468  2.667348 0.025734051
2        1           x 0.5000909 0.1179055  4.241455 0.002169629
..     ...         ...       ...       ...       ...         ...
```

cc @UW-POLS503/spring-2016-students

**Comment by jrnold** [comment]
Also, checkout [this tutorial](https://stat545-ubc.github.io/block023_dplyr-do.html#meet-do) from Stat 545 on using `do`.
