### ISSUE TITLE
Error message when trying to knit PDF

### ISSUE THREAD

**Issue by beatricemagistro** [UW-POLS503/Assignment_01#14]
@jrnold @CasAndreu 

when it's at 98% I get this error message: line 221 error in data.frame(actual=reg1$model$time, predicted=reg1$fitted.values): arguments imply differing number of rows: 0, 11 Calls: <Anonymous>... withCallingHandlers -> withVisible -> eval -> eval -> data.frame Execution halted

the piece of code there is problem 3 c and it works just fine so I don't understand the error message: 

``` r
#c

data2 <- data.frame(actual=reg1$model$time, predicted=reg1$fitted.values)

regs_plot <- ggplot(data2, aes(x=actual, y= predicted))+
  geom_point()+
  geom_smooth(method="lm")

regs_plot
```

**Comment by CasAndreu** [comment]
When you create the `data2` data frame, for some reason the first column `actual` is empty. Did you change the name of the variable `time` in some previous step? A good way to debug this would be to close and re-open your session and start running line by line again (as if you were the compiler), and see how `reg1` looks right before creating `data2` (e.g. ask for `str(reg1)`, and look at the element `model` in `reg1`).

However, if you can't figure it out, you can just turn in the R-Markdown file (`solutions.Rmd`). We don't really need the resulting PDF (`solutions.pdf`). 

cc @UW-POLS503/spring-2016-students

**Comment by beatricemagistro** [comment]
It still does not work! I am not sure what's wrong! I submitted the
solutions.Rmd, hopefully I did it correctly!

**Comment by beatricemagistro** [comment]
Thanks a lot anyways!
